[package]
name = "add_binary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon="*"
rand="0.8"
diam={git="https://github.com/wagnerf42/diam"}